# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f8de7972ae23d3484581d87137829385"
name = "nusense-tryon"
application_url = "https://try-this-look.vercel.app"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kanchi-sarees-2.myshopify.com"

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://try-this-look.vercel.app/auth/callback",
  "https://try-this-look.vercel.app/auth/shopify/callback",
  "https://try-this-look.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://try-this-look.vercel.app"
subpath = "a"
prefix = "apps"

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "nusense-tryon"
